name: Scrape All Malta Hotels

on:
  workflow_dispatch:

jobs:
  scrape_all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run full hotel scraper
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python hotels_all.py

      - name: Upload full results CSV
        uses: actions/upload-artifact@v3
        with:
          name: hotels_all_output
          path: hotels_enriched.csv
