name: Scrape Hotels

on:
  workflow_dispatch:   # run manually from GitHub Actions tab

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Run scraper
        run: python scraper.py

      - name: Upload CSV
        uses: actions/upload-artifact@v4   # ✅ updated to v4
        with:
          name: raw-hotels
          path: raw_hotels.csv
