name: Scrape Hotels (AI Ready)

on:
  workflow_dispatch:  # run manually from the Actions tab

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run hotels AI-ready scraper
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python hotels_ai_ready.py

      - name: Upload CSV
        uses: actions/upload-artifact@v4
        with:
          name: hotels_ai_ready
          path: hotels_ai_ready.csv
